### ISSUE TITLE
Factors

### ISSUE THREAD

**Issue by momba98** [connorferster/forallpeople#11]
Hey! Great repo. It will help me a lot, I'm sure of that.

I got one question. Why does this factor values keep showing every time I call a variable? 

![forall](https://user-images.githubusercontent.com/56093639/91580073-f104b980-e922-11ea-85ea-a28c011f64a5.png)

**Comment by connorferster** [comment]
[facepalm]
...because I left some debugging `print` statements in the code accidentally when I committed and published. Fixing...

**Comment by connorferster** [comment]
Could you do a `forallpeople.__version__` for me? I am trying to find the offending `print()` in the code and I am not finding it. Current version is 2.0.0.

**Comment by momba98** [comment]
Sure. 

Mine is 2.0.0.

**Comment by connorferster** [comment]
Thanks. I have just published a patch to PYPI as version 2.0.1. Run `pip install forallpeople -U` to upgrade in a couple of minutes.
