### ISSUE TITLE
New handcalcs release with forallpeople doesn't render Latex

### ISSUE THREAD

**Issue by BTWS2** [connorferster/forallpeople#15]
````Python
#%%
import handcalcs.render
import forallpeople as si
si.environment('default')
from importlib.metadata import version
print(version('handcalcs'))

#%%
%%render
length = 4 * si.m
width = 3.5 * si.m
area = length * width
area
````
![image](https://user-images.githubusercontent.com/56451049/93821747-4f416580-fc5f-11ea-80da-fe2812e18df7.png)

The new handcalcs release with forallpeople doesn't render the Latex notation. I'm I doing something wrong?

**Comment by connorferster** [comment]
Hi @BTWS2,
Fixed in patch v1.0.3.
