### ISSUE TITLE
Hello and Thank You

### ISSUE THREAD

**Issue by mocquin** [connorferster/forallpeople#17]
Just discovered this package and it looks very interesting ! I am working on a similar package of my own ([physipy](https://github.com/mocquin/physipy)), and after reading your readme, I'm amazed how our implementations are similar.
I would love to be able to discuss with you about some implementation choices. Many thanks ! Cheers

**Comment by connorferster** [comment]
Hi @mocquin,

Yeah, that would be fun. Send me an email to my username "@gmail" and we can schedule something up.

**Comment by mocquin** [comment]
Will do, thanks
