### ISSUE TITLE
Setup.py still claims that the code is under MIT license

### ISSUE THREAD

**Issue by mmohrhard** [connorferster/forallpeople#33]
While the license file and the file headers have been updated to point to Apache 2.0 in https://github.com/connorferster/forallpeople/commit/c381edca1f670a53999e7b6ab2f3cdd011e40c9b the setup.py code still references MIT and therefore e.g. pip claims this the package is still MIT licensed: https://pypi.org/project/forallpeople/

**Comment by connorferster** [comment]
Thanks for pointing this out. Will fix...

**Comment by connorferster** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/38441489/139557745-2cd7c810-c402-4ac9-ab49-d06dbf0bb143.png)
