### ISSUE TITLE
Location of environment .json files.

### ISSUE THREAD

**Issue by JimZwartveld** [connorferster/forallpeople#34]
When installing forallpeople, the environment .json files are stored in the main repository of the package. I'm looking to install forallpeople and add a custom environment to my built package. This is currently quite difficult as my package needs to look up where forallpeople is installed and add the custom environment to the installed package. 

I have two suggestions to overcome this issue;
1) Store the .json files in conda environment \share folder (as jupyter does with its templates). Other packages can add .json files to the share folder.
2) add a function in forallpeople where you can import .json files from other locations. Maybe this is already there, and I just didn't find it. If it's already there you can close this issue :) 

I'm happy to help store the .json files in the share folder.

**Comment by JimZwartveld** [comment]
It wasn't too much work, so I went ahead and implemented point 1 in [PR 35](https://github.com/connorferster/forallpeople/pull/35)

**Comment by connorferster** [comment]
Merged in PR 35
