### ISSUE TITLE
Issues with ksi unit

### ISSUE THREAD

**Issue by SoonerSE** [connorferster/forallpeople#41]
There appears to be an issue with the ksi unit.  
Fy = 50*ksi, prints 50000 psi
Fy = (50*ksi).to("ksi"), prints 344.738 MPa
Is there a way to get it to print 50 ksi?

**Comment by nagatushar** [comment]
I have the same issue. All of my ksis reprint to MPa

**Comment by dataylor3** [comment]
I also have the ksi to MPa issue.  I want to render the values in ksi.  How do you do that?

**Comment by andysazima** [comment]
Same issue. ksi is an important unit in US structural engineering!

**Comment by nagatushar** [comment]
I used pint and just did everything manually

**Comment by connorferster** [comment]
This is now fixed in #47. Thanks for your patience. This frustrated the heck out of me too.
