### ISSUE TITLE
Obtaining the value in a specific unit/factor

### ISSUE THREAD

**Issue by scote89** [connorferster/forallpeople#45]
Could we document how one can obtain a value using "var.value" but in the same way we specified it? ex:

x=25*mm
x.value
----> 0.25

In this example I would like the value to be in the right units and not the converted SI unit (25, not 0.25) and not have to reconvert *1000

**Comment by connorferster** [comment]
Hi @scote89 

Yep! You can use `float()`.

```python
x = 25*mm
float(x) # 25
```
