### ISSUE TITLE
Syntax problem with mathrm for rendering millimeters in forallpeople-2.6.0 and 2.6.1

### ISSUE THREAD

**Issue by felipehuerta17** [connorferster/forallpeople#55]
Dear Connor,

I have been using handcalcs with forallpeople extensively for creating teaching material for a Unit Operations course that I am giving. It has been incredibly helpful.

Unfortunately, with the last release the millimeters are not rendering properly. With forallpeople-2.6.0,

The following code
```python
%%render
d_i = 19.05e-3 * m 
d_o = 20.05e-3 * m
N_t = 56 # El flujo se divide entre 326 tubos
a_t = N_t * (pi * d_i**2/4) # 0.2 p
G_t = F_h/a_t
Re_D = G_t*d_i/(mu_h) # 0.1 p
```
Produces the following output

![image](https://user-images.githubusercontent.com/33637198/177453358-f38b5cd8-c06b-47bd-b951-a10fa2569988.png)

We can see that an extra 'm' is appended after \mathrm, producing \mathrmm and hence providing a broken output.

This does not happen with forallpeople-2.5.0, and that's what I am using at the moment.

I have the intuition that the problem may be in the file physical_helper_functions.py

Best wishes
Felipe

**Comment by connorferster** [comment]
This is fixed in v2.6.2 :)
