### ISSUE TITLE
Latex prefix syntax issue for all base units

### ISSUE THREAD

**Issue by jonpecar** [connorferster/forallpeople#56]
When rendering a value in LaTeX using any of the base units (s, A, mol etc.) the prefix is inserted in the wrong position in the LaTeX string. For example, for a value of 5,000 kA, LaTeX would be generated as `\mathrkm{A}` when expected output would be `\mathrm{kA}`.

I have checked for a number of different units and it appears to only happen with base units. Derived units seem unaffected.

**Comment by connorferster** [comment]
Thanks for the PR @jonpecar!
